import Head from "next/head";
import {useContext} from "react";
import {Context} from "../../pages/_app";

const Seo = ({pageTitle, font}) => {
    const {config} = useContext(Context);
    return (<Head>
        <title>
            {pageTitle ? `${pageTitle} | ${config?.NEXT_PUBLIC_COMPANY_NAME}` : config?.NEXT_PUBLIC_COMPANY_NAME}
        </title>
        <meta httpEquiv="x-ua-compatible" content="ie=edge"/>
        <meta name="description" content="Generated by create next app"/>
        <meta name="robots" content="noindex, follow"/>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link href={font} rel="stylesheet"/>
        <link
            rel="shortcut icon"
            href={config?.NEXT_PUBLIC_COMPANY_FAVICON ? JSON.parse(config?.NEXT_PUBLIC_COMPANY_FAVICON)[0].fileUrl : "../public/uploads/defaultImage.png"}
        />
    </Head>);
};

export default Seo;
